/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'outline-variant': '#5c403c',
        'tertiary-fixed': '#e3e2e2',
        'inverse-surface': '#e5e2e1',
        'on-surface': '#e5e2e1',
        'surface-bright': '#393939',
        'surface-dim': '#131313',
        'on-primary-fixed-variant': '#93000b',
        'on-secondary-fixed-variant': '#8f1015',
        'secondary-fixed-dim': '#ffb3ac',
        'on-tertiary-fixed': '#1a1c1c',
        'on-primary-fixed': '#410002',
        'inverse-primary': '#bf0715',
        'surface-tint': '#ffb4ab',
        'surface-container-highest': '#353534',
        'error': '#ffb4ab',
        'on-secondary': '#680008',
        'on-primary': '#690005',
        'primary-container': '#dc2626',
        'surface-variant': '#353534',
        'on-primary-container': '#fff6f5',
        'primary-fixed-dim': '#ffb4ab',
        'on-secondary-fixed': '#410003',
        'inverse-on-surface': '#313030',
        'secondary-container': '#8f1015',
        'primary': '#ffb4ab',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'primary-fixed': '#ffdad6',
        'on-tertiary': '#2f3131',
        'on-error': '#690005',
        'on-background': '#e5e2e1',
        'tertiary-container': '#717272',
        'surface-container-high': '#2a2a2a',
        'secondary-fixed': '#ffdad6',
        'error-container': '#93000a',
        'on-tertiary-fixed-variant': '#464747',
        'on-surface-variant': '#e6bdb8',
        'tertiary': '#c7c6c6',
        'surface': '#131313',
        'secondary': '#ffb3ac',
        'outline': '#ac8884',
        'on-error-container': '#ffdad6',
        'background': '#131313',
        'on-tertiary-container': '#f9f8f8',
        'tertiary-fixed-dim': '#c7c6c6',
        'surface-container': '#201f1f',
        'on-secondary-container': '#ff9990',
      },
      fontFamily: {
        headline: ['Inter', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'Courier New', 'monospace'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      animation: {
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'fade-in': 'fadeIn 0.4s ease-in-out',
        'slide-up': 'slideUp 0.4s ease-out',
        'fly-to-cart': 'flyToCart 0.6s ease-in-out forwards',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        slideUp: {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        flyToCart: {
          '0%': { transform: 'scale(1) translate(0, 0)', opacity: '1' },
          '100%': { transform: 'scale(0) translate(300px, -400px)', opacity: '0' },
        },
      },
    },
  },
  plugins: [],
};
